### ISSUE TITLE
Credit

### ISSUE THREAD

**Issue by VillainsRule4000** [BilbertRules/BlooketHelper#2]
I am a collaborator on [this](https://github.com/Hankypoo7/Blooket-hacks-Hankypoo7-) repository. I think your "helpers" are very interesting and am wondering if you are okay with me adding them (and giving credit, of course).

**Comment by BilbertRules** [comment]
ah, yes. lol-jude made the token one.

**Comment by VillainsRule4000** [comment]
Thanks!
